import { cva } from 'class-variance-authority';
import Image from 'next/image';
import BadUIDesignImg from '@/images/bad-ui-showcase.png';
import { RoastUISystemSvg } from '../RoastUISystemSvg';
import { DrawnArrowVerticalSvg } from '../drawnArrowVerticalSvg';

const container = cva('flex flex-col items-center w-full max-w-screen-sm');

const topContainer = cva('flex flex-col items-center');
const middleContainer = cva('flex flex-col w-full lg:w-[550px]');
const bottomContainer = cva('flex gap-x-10');

const outputItem = cva('flex flex-col w-full items-center');
const outputLabel = cva(
  'text-sm lg:text-xl text-white font-semibold max-w-56 text-center flex flex-col items-center',
);

const outputNumber = cva(
  'text-lg text-gray-400 absolute top-[50%-10px] right-[calc(50%-20px)]',
);

const arrow = cva('flex relative w-5', {
  variants: {
    size: {
      default: 'h-14 my-8',
      small: 'h-10 my-6',
    },
  },
  defaultVariants: {
    size: 'default',
  },
});

const badUIDesignImage = cva('w-72 lg:w-96');

const label = cva('text-md text-gray-400 mt-4');

export function WorkFlow() {
  return (
    <div className={container()}>
      <div className={topContainer()}>
        <Image
          src={BadUIDesignImg.src}
          width={BadUIDesignImg.width}
          height={BadUIDesignImg.height}
          alt="Bad UI design"
          className={badUIDesignImage()}
        />
        <span className={label()}>Your design</span>
      </div>
      <span className={arrow()}>
        <DrawnArrowVerticalSvg />
      </span>
      <div className={middleContainer()}>
        <RoastUISystemSvg />
      </div>
      <div className={bottomContainer()}>
        <div className={outputItem()}>
          <span className={arrow({ size: 'small', className: 'w-10' })}>
            <DrawnArrowVerticalSvg />
            <span className={outputNumber()}>1</span>
          </span>
          <p className={outputLabel()}>Uncover UI/UX design mistakes ❌/✅</p>
        </div>
        <div className={outputItem()}>
          <span className={arrow({ size: 'small', className: 'w-10' })}>
            <DrawnArrowVerticalSvg />
            <span className={outputNumber()}>2</span>
          </span>
          <p className={outputLabel()}>
            Improved UI/UX design generated by AI ✨
            <span className="text-sm text-gray-400 font-light">
              + Source Code
            </span>
          </p>
        </div>
      </div>
    </div>
  );
}
